### ISSUE TITLE
Step 8, Line 151

### ISSUE THREAD

**Issue by megwangrpf** [raspberrypilearning/getting-started-scratch#107]
At the moment, the blocks are referred to as “set volume to{:class="block3sound"} and set sound effect to{:class="block3sound"} blocks”, but in the recent ‘More Scratch’ pathway, these blocks have been written as set volume to (){:class="block3sound"} and set ()effect to (){:class="block3sound"} blocks’. Which do you prefer?

**Comment by libxx1** [comment]
I've changed it slightly so it doesn't talk about a `set sound effect to` block and instead says `set pitch to` and `set pan to` separately. 

If it's in a general instruction sentence we write in in the way that's easiest to read so we don't include [ v] () but if it's a specific instruction to drag a block over and change the values in the block to match our project code then we would include the brackets.
