### ISSUE TITLE
Step 20

### ISSUE THREAD

**Issue by megwangrpf** [raspberrypilearning/getting-started-scratch#110]
We repeat how to fill in the Notes and Credits, and how to share your project website, because they are part of the [[[share-scratch]]] ingredient. I wonder if it makes more sense to have the [[[share-scratch]]] first, then the Scratch project Instructions and Notes and Credits section, followed by the Share your Scratch project's web address section? Do these sections repeat as ingredients elsewhere? (I’m assuming not, since they aren’t stand-alone ingredients.) If not, then we could combine these sections and name it ‘More on sharing your project’. Same with the commenting section. How do we normally deal with information that is a bit cross-over or repeated?

**Comment by libxx1** [comment]
I've reordered it. What do you think? It's got the share-scratch ingredient then two additional bits of information on the web address and what to put in notes and comments so it's not telling them how to do it again it's just giving them ideas on what is useful to type in there? 

Usually we wouldn't have any repeatable information. If the ingredient wasn't exactly what we needed we'd just do a collapse. The guide is a little bit different in that it's making use of ingredients designed for projects. 

Does this work as it is now?

**Comment by megwangrpf** [comment]
That's great, Liz!
